### ISSUE TITLE
[bug] use this plugin in vue find a error that is  Cannot read property 'addModal' of undefined

### ISSUE THREAD

**Issue by markflyfly** [Egorvah/vudal#1]
## this is use code 
`
<vudal name="cropImageModel">
      <div class="header">
        <i class="close icon"></i>
        裁剪图片
      </div>
      <div class="content">
        <el-row>
          <img id="crop_image" :src="cropImageSrc" width="100%" height="100%">
        </el-row>
      </div>
      <div class="actions">
        <div @click="cropImage = false" class="ui cancel button">取消</div>
        <div @click="submitCrop" class="ui button">确定</div>
      </div>
    </vudal>
`
## this is import code:  
`
  import Vue from "vue"  
 import Vudal from 'vudal';
`
 
## and set to the components   
`
components: {
        'ElUpload': ElUpload,
        "ElDialog": ElDialog,
        "ElButton":ElButton,
        "ElRow":ElRow,
        "draggable": draggable,
        "vudal": Vudal
    }
`
## this is error:

![qq 20170706181113](https://user-images.githubusercontent.com/15846359/27906533-83e45dd2-6276-11e7-9af1-03c993567bab.jpg)
![image](https://user-images.githubusercontent.com/15846359/27906644-0219e73a-6277-11e7-94fd-4d8e0ef6de14.png)

**Comment by Egorvah** [comment]
Hello
I think problem because you don't use VudalPlugin

for example:
`
import Vue from 'vue';
import { VudalPlugin } from 'vudal';

 Vue.use(VudalPlugin);
`
 and next use component vudal
